### ISSUE TITLE
 Accessories must be created with a non-empty displayName

### ISSUE THREAD

**Issue by mokrol** [codyc1515/homebridge-orbit-bhyve#14]
Just updated my plugin and had this happen:

```
_Oct 29 08:47:32 raspberrypi homebridge[4655]: [10/29/2019, 8:47:32 AM] Initializing OrbitBHyve accessory...
Oct 29 08:47:32 raspberrypi homebridge[4655]: [10/29/2019, 8:47:32 AM] **Error: Accessories must be created with a non-empty displayName**.
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:49:27)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:445:21)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:309:26)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at startup (internal/bootstrap/node.js:283:19)
Oct 29 08:47:32 raspberrypi homebridge[4655]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Oct 29 08:47:32 raspberrypi homebridge[4655]: [10/29/2019, 8:47:32 AM] **Got SIGTERM, shutting down Homebridge**..._
```
This is what I had in my config file:

> "email": "Email address",            
> "password": "my password",            
> "zones": 5,            
> "debug": true,            
> "accessory": "OrbitBHyve"

I had to remove from the config file to get Homebridge to load again. That being said, I have not been able to get this plugin to work right for me. I have 5 stations but only 4 display on HB. I can't turn anything on or off from HB. 

I am also running HB as a service so I'm not sure if that is contributing to the issue.

**Comment by mokrol** [comment]
@codyc1515 - Any thoughts here? I uninstalled the app and reinstalled and the same issue. I get the following **Error: Accessories must be created with a non-empty displayName**

**Comment by codyc1515** [comment]
You need a name parameter in your config.

**Comment by apexad** [comment]
As in:
```
"email": "Email address",
"password": "my password",
"zones": 5,
"debug": true,
"accessory": "OrbitBHyve",
"name": "Sprinkler"
```

**Comment by mokrol** [comment]
Thanks! that fixed it.
