### ISSUE TITLE
Crashes after a while.

### ISSUE THREAD

**Issue by DR2000** [codyc1515/homebridge-orbit-bhyve#4]
Keeps working for several day and then eventually crashes with the following:

TypeError: Cannot read property '0' of undefined
    at BHyveValve.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/index.js:139:82)
    at Array.forEach (<anonymous>)
    at BHyveValve.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/index.js:123:12)
    at Request.self.callback (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by codyc1515** [comment]
This will happen if the Orbit API does not return any devices. I will add some error checking for this.

**Comment by platini76** [comment]
it happens to me only now... why in 2 months does not happens?

**Comment by codyc1515** [comment]
This should be resolved now.

Can you please:

- Update and try again
- Was this working for you before?
- Which device are you are using?

By chance, do you happen to have the device set to "auto" mode? If so, this should be fixed now as well.

**Comment by platini76** [comment]
thanks.
I use Orbit B-hyve 94990
before it works very well for august and sept... no problems..


it seems now working ok.. not taking the state when on from homekit app... it say waiting...

**Comment by codyc1515** [comment]
Hi there @platini76, can you please try with the latest version and let me know if you are still experiencing any issues? Also what is your expectation of the behaviour of the plug-in vs. what is happening? I am using the same device as you.
