### ISSUE TITLE
Multi Station WiFi Irrigation Controller

### ISSUE THREAD

**Issue by mitch7391** [codyc1515/homebridge-orbit-bhyve#6]
Excited about your work so far :) are there any plans to get this to work for the multi station WiFi irrigation controllers? Thanks in advance.

**Comment by dodavies** [comment]
that would be awesome

**Comment by mitch7391** [comment]
@codyc1515 if I was to buy this controller would it aid you in adding this integration? We have limited time rebate in Western Australia for smart irrigation controllers and now would be the time for me to jump on this one, otherwise I might just go another brand if I cant guarantee homekit.

**Comment by dodavies** [comment]
I also have the 6 station wifi controller

**Comment by codyc1515** [comment]
Hi @dodavies @mitch7391 !

If either of you have the device are you able to please send me an email with your login details to codyc1515@icloud.com? As I don't have this device I do not see any other way to make this work. This will only be so that I can take a look at the device and see about adding support.

Just to be clear, I believe that this one has wifi and works through the standard Orbit B-Hyve app, right?

Cheers :)

**Comment by mitch7391** [comment]
Hey @codyc1515 I still haven’t bought the unit yet (life has been pretty busy lately). Once I have I will let you know straight away.

And you are correct, it uses the b-hyve app and it uses wifi :) thanks for looking into this one!

**Comment by dodavies** [comment]
Given the season in the UK my unit is isolated from the water supply, I will send over a login.

**Comment by codyc1515** [comment]
I have added support for multi-zone controllers now. Simply change your config.json file to reflect something similar to the following:

```
        {
            "accessory": "OrbitBHyve",
            "name": "Orbit B-Hyve",
            "email": "joe@bloggs.com",
            "password": "mySECUREpassword",
            "zones": 4
        }
```

Please let me know your feedback once you have had a chance to try it.

An important note: the Orbit API only allows one Zone to be running at a time, even though HomeKit supports multiple. This means when you turn on one zone, it will turn off the others. Disappointing but still good to have the control over the other zones.

I am also aware that there appears to be an issue with the Remaining Duration, but this seems to be a somewhat minor issue.

**Comment by dodavies** [comment]
Looking great, I kept getting in home bridge the following messaging, so I went into each zone and set a default time of ten minutes and the messages stopped.

The log also talks about battery level, these units are mains powered with no battery (other then the lithium button for clock backup) can this be surpressed or removed with config flag ?

Superb work though, thank you ever so much, I have left the login the same if you need to test further.

[10/20/2019, 4:41:42 PM] [Irrigation] No battery service available
[10/20/2019, 4:41:42 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/20/2019, 4:41:49 PM] [Irrigation] No battery service available
[10/20/2019, 4:41:49 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/20/2019, 4:42:10 PM] [Irrigation] No battery service available
[10/20/2019, 4:42:10 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/20/2019, 4:43:32 PM] [Irrigation] No battery service available
[10/20/2019, 4:43:32 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/20/2019, 4:43:43 PM] [Irrigation] No battery service available
[10/20/2019, 4:43:43 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes

**Comment by dodavies** [comment]
actually, the message re Unknown preset runtime, leaving default of 5 minutes keeps coming ..

**Comment by dodavies** [comment]
further update, I tried asking Siri to switch on zone 1, it said it couldn't as it wasn't supported, so I asked again to switch on irrigation, which it did, turning on zone three, then it borked.

[10/20/2019, 4:55:36 PM] [Irrigation] No battery service available
[10/20/2019, 4:55:36 PM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/20/2019, 4:55:36 PM] [Irrigation] WS | change_mode
[10/20/2019, 4:55:36 PM] [Irrigation] WS | watering_in_progress_notification Station 2 Runtime 5
[10/20/2019, 4:55:36 PM] [Irrigation] WS | change_mode
[10/20/2019, 4:55:36 PM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:327
      throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
      ^

Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:327:13)
    at BHyveValve.open (/usr/local/lib/node_modules/homebridge-orbit-bhyve/index.js:496:24)
    at WebSocket.emit (events.js:197:13)
    at WebSocket.setSocket (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:172:10)
    at ClientRequest.req.on (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:646:15)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketOnData (_http_client.js:482:11)
    at TLSSocket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)

**Comment by mitch7391** [comment]
Oh wow awesome work @codyc1515 , I just got mine installed last night and can also try some stress testing after work today :) I am not sure if everyone’s irrigation systems are set up this way, but houses I have rented in the past and now my own house only allow for one zone at a time (or maybe it was the limitation of the dumb controllers). So I don’t think that would be an issue, if anything running more than one zone at a time could cause low pressure issues due to the mains water supply.

**Comment by mitch7391** [comment]
I used the suggested config above and installed the plugin, but it seems to kill my homebridge with the following error:

Oct 21 20:35:22 homebridge homebridge[15862]: [10/21/2019, 8:35:22 PM] [Broadlink RM] [INFO] Discovered Broadlink RM2 Pro Plus v2 (2787) at 192.168.0.154 (34:ea:34:99:f1:28)
Oct 21 20:35:22 homebridge homebridge[15862]: [10/21/2019, 8:35:22 PM] [CMD Switch] Kodi is off.
Oct 21 20:35:23 homebridge homebridge[15862]: [10/21/2019, 8:35:23 PM] [Broadlink RM] TV getSwitchState: true
Oct 21 20:35:24 homebridge homebridge[15862]: [10/21/2019, 8:35:24 PM] [Harrisdale] Observations retrieved.
Oct 21 20:35:24 homebridge homebridge[15862]: [10/21/2019, 8:35:24 PM] [Harrisdale] BOM data will expire at 1571661000000 which is in -5.3min
Oct 21 20:35:25 homebridge homebridge[15862]: SyntaxError: Unexpected token A in JSON at position 0
Oct 21 20:35:25 homebridge homebridge[15862]:     at JSON.parse (<anonymous>:null:null)
Oct 21 20:35:25 homebridge homebridge[15862]:     at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-cmd4/node_modules/github-version-checker/lib/check.js:64:21)
Oct 21 20:35:25 homebridge homebridge[15862]:     at IncomingMessage.emit (events.js:198:15)
Oct 21 20:35:25 homebridge homebridge[15862]:     at endReadableNT (_stream_readable.js:1139:12)
Oct 21 20:35:25 homebridge homebridge[15862]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
Oct 21 20:35:25 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=255/n/a
Oct 21 20:35:25 homebridge systemd[1]: homebridge.service: Unit entered failed state.
Oct 21 20:35:25 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.

Haven't seen that one before, will have to do a big of digging for what could be wrong.

**Comment by mitch7391** [comment]
Ok scrap that, I stopped homebridge service and reset my password inside the Orbit app. Restarted the homebridge service and it is working now. Wont do any testing of commands tonight as night watering can promote fungus in my lawn haha... 

As it stands it shows the sprinkler as one accessory (due to ios13 grouping) and says it is 'scheduled' as a status on the accessory tile (which is cool), with the grouped accessories inside showing my four zones. Each zone allows me to set a timer (not tested yet) and also allows for me to disable zones (handy for restricted months). It also states on the main group that the battery level is 100% but it is not charging; which as dodavies mentioned above, these are hardwired to the mains power supply.

**Comment by dodavies** [comment]
I have left the login the same if you need to test further.

**Comment by mokrol** [comment]
I can't get my 5th station to show up. I have the following in my config file:


```
{
	     "accessory": "OrbitBHyve",
	     "name": "Orbit B-Hyve",
	     "email": "<my email>",
	     "password": "<my password>",
	     "zones": "5"
  }
```

I also tried the Zones without the quotes as shown above and still no luck.

**Comment by mitch7391** [comment]
Did a bit of testing tonight and I can’t get it to run from HomeKit. The feedback to HomeKit seems fine, but I can’t issue any start commands, it is just saying ‘waiting’ when I switch it on, but doesn’t progress any further. Siri will tell me she has turned it one, but it does nothing. The strange thing is I also don’t see it issue any commands from Homebridge logs... @dodavies did you get further than this and get the sprinkler to start?

**Comment by dodavies** [comment]
Yes it starts each zone from the home app on the computer or phone with no issue, it all goes pear shaped if i try Siri as i posted above

**Comment by dodavies** [comment]
the app does weird things though, each slider goes up then down saying waiting


[10/22/2019, 11:08:13 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:14 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:14 AM] [Irrigation] WS | watering_in_progress_notification Station 3 Runtime 5
[10/22/2019, 11:08:15 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:15 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:15 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:16 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:25 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:25 AM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/22/2019, 11:08:34 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:34 AM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/22/2019, 11:08:34 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:34 AM] [Irrigation] Unknown preset runtime, leaving default of 5 minutes
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:35 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:35 AM] [Irrigation] WS | watering_in_progress_notification Station 4 Runtime 5
[10/22/2019, 11:08:41 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:41 AM] [Irrigation] No battery service available
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | watering_complete
[10/22/2019, 11:08:42 AM] [Irrigation] WS | change_mode
[10/22/2019, 11:08:42 AM] [Irrigation] WS | change_mode

**Comment by mitch7391** [comment]
Hmm yeah mine does the up and down thing sometimes but must of the time it will stay in the on position and say waiting; whilst not doing anything. Can I please see your config?

**Comment by dodavies** [comment]
{
                "accessory": "OrbitBHyve",
                "name": "Irrigation",
                "email": "blahblah@gmail.com",
                "password": "blahblahblah",
                "zones": 4
                 },

**Comment by mitch7391** [comment]
Strange, it’s no different to my config...

**Comment by dodavies** [comment]
Did you try it with four zones?
Mine has six but only four are plumbed in

**Comment by mitch7391** [comment]
Yeah I only have four zones anyway :)

**Comment by mitch7391** [comment]
My sprinklers were scheduled for this morning, I can see they are on in the B-Hyve app, but HomeKit feedback still says they are off and scheduled. Really not sure what is going on, will have to do some more digging when I’m on days off.

**Comment by codyc1515** [comment]
Hey all - just need to clear up a few things.

**Push vs. Pull**: This accessory will only update itself when you open the Home app. If you turn on the valve(s) from outside of the Home app, i.e. in the Orbit app, the Home app will not know unless you open it. We could check for changes using the Web Sockets API used in the mobile app... except that it closes inexplicably every 30 seconds. This means that we could poll constantly, but I don't know if Orbit would appreciate that.

**Battery**: The battery thing is a cosmetic issue. There's a bug somewhere, but I cannot find it. Technically the plug-in is sending a flag to say that the battery is not chargeable. I have also tried hiding the service, but it just doesn't work.

**Zones**: Currently only 4 zones are supported (up from 1). I can easily add the other four (make it up to 8, I think this is the max they offer), however, the Orbit API only allows one zone to be running at a time from what I can tell. So we have to replicate this behaviour in the Homebridge accessory which is fairly difficult.

**Siri**: Seems to be a bit wonky from the comments here and that has been my experience also. I filed a bug for one of the issues, but haven't heard back from Apple yet. The same issue happens in the HomeKit Accessory Simulator.

_Going forward can we please, raise any new issues as a **new** issue :)_

Hope this helps.

Cody

**Comment by mitch7391** [comment]
Thanks for addressing the original request and adding the functionality. Also thanks for the above info, I will open new issues as I go :)

**Comment by mitch7391** [comment]
@dodavies were you setting the default run time form Homebridge or HomeKit? I notice mine in HomeKit keep defaulting back to 5mins after I set them to 15mins, Iv had to do this at least 5 times now. Just double checking it’s not a config thing to set it.

**Comment by dodavies** [comment]
From the Home app on my iPhone

**Comment by mitch7391** [comment]
Thanks for the info, that is where I have been changing mine but it keeps reverting.
