### ISSUE TITLE
homebrighe shutting down cycle

### ISSUE THREAD

**Issue by platini76** [codyc1515/homebridge-orbit-bhyve#7]
[2019-10-5 8:34:35 PM] TypeError: Cannot read property '0' of undefined
    at BHyveValve.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/index.js:139:82)
    at Array.forEach (<anonymous>:null:null)
    at BHyveValve.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/index.js:123:12)
    at Request.self.callback (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-orbit-bhyve/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-10-5 8:34:35 PM] Got SIGTERM, shutting down Homebridge...

**Comment by codyc1515** [comment]
This should be resolved now.

Can you please:

- Update and try again
- Was this working for you before?
- Which device are you are using?

**Comment by codyc1515** [comment]
Closing due to no response.

**Comment by mitch7391** [comment]
Hey @codyc1515 I think since updating I am having this issue? When before my orbit was not registering anything on homebridge logs (only the 'log in' and the 'battery service' logs). Now I have issued a run command of zone 1 from homekit and it killed my session with the following error:

Oct 23 18:50:40 homebridge homebridge[10651]: [10/23/2019, 6:50:40 PM] Error: WebSocket is not open: readyState 0 (CONNECTING)
Oct 23 18:50:40 homebridge homebridge[10651]:     at WebSocket.send (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:327:13)
Oct 23 18:50:40 homebridge homebridge[10651]:     at BHyveValve.open (/usr/local/lib/node_modules/homebridge-orbit-bhyve/index.js:501:24)
Oct 23 18:50:40 homebridge homebridge[10651]:     at WebSocket.emit (events.js:193:13)
Oct 23 18:50:40 homebridge homebridge[10651]:     at WebSocket.setSocket (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:172:10)
Oct 23 18:50:40 homebridge homebridge[10651]:     at ClientRequest.req.on (/usr/local/lib/node_modules/homebridge-orbit-bhyve/node_modules/ws/lib/websocket.js:646:15)
Oct 23 18:50:40 homebridge homebridge[10651]:     at ClientRequest.emit (events.js:193:13)
Oct 23 18:50:40 homebridge homebridge[10651]:     at TLSSocket.socketOnData (_http_client.js:480:11)
Oct 23 18:50:40 homebridge homebridge[10651]:     at TLSSocket.emit (events.js:193:13)
Oct 23 18:50:40 homebridge homebridge[10651]:     at addChunk (_stream_readable.js:295:12)
Oct 23 18:50:40 homebridge homebridge[10651]:     at readableAddChunk (_stream_readable.js:276:11)
Oct 23 18:50:40 homebridge homebridge[10651]:     at TLSSocket.Readable.push (_stream_readable.js:231:10)
Oct 23 18:50:40 homebridge homebridge[10651]:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:154:17)
Oct 23 18:50:40 homebridge homebridge[10651]: [10/23/2019, 6:50:40 PM] Got SIGTERM, shutting down Homebridge...
